setA=int(input("Enter the first number: "))
setB=int(input("Enter the second number: "))    
setC=setA + setB
print("The sum of setA and setB is :", setC)
print("The difference of setA and setB is :", setA - setB)
print("The product of setA and setB is :", setA * setB) 
print("The division of setA and setB is :", setA / setB)
print("The modulus of setA and setB is :", setA % setB)
print("The exponentiation of setA and setB is :", setA ** setB)
print("The floor division of setA and setB is :", setA // setB)
print("The average of setA and setB is :", (setA + setB) / 2)
print("The maximum of setA and setB is :", max(setA, setB))
print("The minimum of setA and setB is :", min(setA, setB))
print("The absolute value of setA is :", abs(setA))
print("The absolute value of setB is :", abs(setB))
print("The square root of setA is :", setA ** 0.5)
print("The square root of setB is :", setB ** 0.5)
print(f"The sum of setA and setB is {setC}, the difference is {setA - setB}, the product is {setA * setB}, the division is {setA / setB}, the modulus is {setA % setB}, the exponentiation is {setA ** setB}, and the floor division is {setA // setB}.")
print(f"The average of setA and setB is {(setA + setB) / 2}, the maximum is {max(setA, setB)}, the minimum is {min(setA, setB)}, the absolute value of setA is {abs(setA)}, the absolute value of setB is {abs(setB)}, the square root of setA is {setA ** 0.5}, and the square root of setB is {setB ** 0.5}.")