# Real-World Use Case: Creating a Simple Log File for a Script
# Let’s say you're running a Python script that processes user data. After the script runs, you want to write a log file that documents what happened.

# python
# Copy
# Edit
# Real-world example: Writing log data after processing
processed_users = ["Alice", "Bob", "Charlie"]
with open("logfile.txt", "w") as log:
    log.write("User Data Processing Log\n")
    log.write("========================\n")
    for user in processed_users:
        log.write(f"Processed user: {user}\n")
    log.write("All users processed successfully.\n")
    log.write("Log generated by: https://www.example.com/app\n")